version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: my-postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network

volumes:
  postgres-data:

networks:
  my-network:
    driver: bridge
